/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;

/**
 *
 * @author Windows 10
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Component_HiScore = new javax.swing.JLabel();
        Component_Score2 = new javax.swing.JLabel();
        textScore = new javax.swing.JLabel();
        textHiScore = new javax.swing.JLabel();
        btAnsLeft = new javax.swing.JButton();
        btAnsRight = new javax.swing.JButton();
        Word = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Component_HiScore.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        Component_HiScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Component_HiScore.setText("Hi-Score");

        Component_Score2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        Component_Score2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Component_Score2.setText("Score");

        textScore.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        textScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textScore.setText("00");

        textHiScore.setFont(new java.awt.Font("Segoe UI Semibold", 2, 24)); // NOI18N
        textHiScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textHiScore.setText("00");

        btAnsLeft.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btAnsLeft.setText("Ans1");
        btAnsLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnsLeftActionPerformed(evt);
            }
        });

        btAnsRight.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btAnsRight.setText("Ans2");
        btAnsRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnsRightActionPerformed(evt);
            }
        });

        Word.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        Word.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Word.setText("Word");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Component_Score2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textScore, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(btAnsLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Component_HiScore, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textHiScore, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAnsRight, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(Word, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textScore)
                    .addComponent(Component_Score2)
                    .addComponent(Component_HiScore)
                    .addComponent(textHiScore))
                .addGap(66, 66, 66)
                .addComponent(Word, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnsLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAnsRight, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAnsLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnsLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnsLeftActionPerformed

    private void btAnsRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnsRightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAnsRightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Component_HiScore;
    private javax.swing.JLabel Component_Score2;
    private javax.swing.JLabel Word;
    private javax.swing.JButton btAnsLeft;
    private javax.swing.JButton btAnsRight;
    private javax.swing.JLabel textHiScore;
    private javax.swing.JLabel textScore;
    // End of variables declaration//GEN-END:variables
}
